[gdrive]
type = drive
scope = drive
token = {"access_token":"ya29.a0Aa7pCA9Tf4h6XmcNeQbWIHrDXwj7t7Q7D-Eck7Hrt1R5NNPWOsy6FmtiklyXRO6HHeGrs-oCV8NCPiRfEBEi4C9QM6a_J6OvlL5iEFVwDu8ES1AkwzdDWFvtrt75BiFLWYW9GNKRBWpbfpEWzHzT0X7-SKTxO6G9euyUmOqPzI4Dowfb0XwvleujXbJZz13emHtvQAwaCgYKASoSARMSFQHGX2MiiFb6-w7OsTpzr8qd6L58gQ0206","token_type":"Bearer","refresh_token":"1//0gR_9fv0U1YFACgYIARAAGBASNwF-L9Ir_DGZykK08Wu3LEGmNj5RPLS079zrEgeTlwMjtglqiMuKKMDXGGLTkgIGlar6OBRUEYk","expiry":"2026-01-01T07:02:26.56330653+05:30","expires_in":3599}
team_drive = 

